# Generated by Django 3.1.2 on 2020-10-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salasah', '0002_auto_20201022_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='varian',
            field=models.ManyToManyField(blank=True, null=True, to='Salasah.Varian'),
        ),
    ]
